const splideOptions = [
    "type",
    "rewind",
    "speed",
    "rewindSpeed",
    "rewindByDrag",
    "autoWidth",
    "autoHeight",
    "start",
    "perPage",
    "perMove",
    "focus",
    "gap",
    "arrows",
    "pagination",
    "drag",
    "snap",
    "autoplay",
    "interval",
    "pauseOnHover",
    "keyboard",
    "wheel",
    "direction",
    "trimSpace",
    "omitEnd",
];

export default splideOptions;